angular.module('ServiceModule').service('SessionService',
[ '$http', '$log', '$cookies', '$state', 'RestService', 'SERVICE_URL',
function($http, $log, $cookies, $state, RestService, SERVICE_URL) {

    var functionSet = {
        
        setUser: function(user){
            this.loggedUser = user;
            RestService.http(RestService.TYPE.get, SERVICE_URL.backend + SERVICE_URL.user +"/" + this.loggedUser.id)
            .then(function(response) {
                this.loggedUserData = response;
            }, function(response) {
                $log.info("Error al obtener el usuario");
            });
        },

        getUser: function(){
            return this.loggedUser;
        },

        getUserData: function(){
            return this.loggedUserData;
        },

        logout: function() {
            $cookies.remove("access_token",{path:"/"});
            window.location.assign("../../modules/wait/");
        },

        userHasAutogeneratedPassword : function(){
            if(this.getUser() == undefined) {
                return;
            }
            if (this.getUser().autogenerated) {
                $state.go("changePassword");
            }
        }

    };

    this.getUser = function() {
        return functionSet.getUser();
    };

    this.getUserData = function() {
        return functionSet.getUserData();
    };

    this.logout = function() {
        functionSet.logout();
    };

    this.userHasAutogeneratedPassword = function(){
        functionSet.userHasAutogeneratedPassword();
    }

    this.validateSession = function(){
        var accessToken = $cookies.get("access_token");        
        if(accessToken == undefined || accessToken == null){
            $log.info("No hay sesion iniciada");
            this.loggedUser = undefined;
            //window.location.assign("../../modules/wait/");
            return;
        }
        $log.info("Se encontro sesion iniciada");
        var headers = {Authorization : 'Bearer ' + accessToken};
        RestService.httpHeaders(RestService.TYPE.get, SERVICE_URL.profileUser,undefined, headers)
        .then(function(response) {
            functionSet.setUser(response);
            functionSet.userHasAutogeneratedPassword();
        }, function(response) {
            $log.info("Error obteniendo el perfil");
            functionSet.logout();
        });
    };

    this.executeIfUser = function(funcExecute){
        if(this.getUserData != undefined){
            funcExecute();
        } else {
            console.log("ESPERANDO getUserData");
            $timeout(function(){
                this.executeIfUser(funcExecute);
            }, 200);
        }
    };

}]);
