angular.module('MainModule',['ngMaterial', 'ngMessages','ngAnimate','ngCookies', 'ui.router', 'ui.router.modal', 'ui.select', 'ui.bootstrap','isteven-multi-select', 'CommonsModule', 'ServiceModule', 'UtilsModule', 'ValidateModule']);
angular.module('MainModule').config(function($stateProvider) {

/* INICIO - DEFINICION DE ESTADOS */
/* FIN - DEFINICION DE ESTADOS */ //NO BORRAR NUNCA ESTA LINEA

});

angular.module('MainModule').run(function($transitions, $rootScope, SessionService) {
    SessionService.validateSession();
    $transitions.onSuccess({},function($transition$) {
        $rootScope.previousState = $transition$.$from();
        $rootScope.currentState = $transition$.to();
        if ($rootScope.currentState.name != "changePassword") {
            SessionService.userHasAutogeneratedPassword();
        }
    });

});

